spring.application.name=ibe

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/IBE_DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.jakarta.persistence.jdbc.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/IBE_DB}
spring.jpa.properties.jakarta.persistence.jdbc.user=${SPRING_DATASOURCE_USERNAME:postgres}
spring.jpa.properties.jakarta.persistence.jdbc.password=${SPRING_DATASOURCE_PASSWORD:1234}

# SQL Init
spring.sql.init.mode=never

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# AWS SES
aws.region=${AWS_REGION:ap-south-1}
aws.ses.from-email=${AWS_SES_FROM_EMAIL:hari.k@kickdrumtech.com}
aws.ses.enabled=${AWS_SES_ENABLED:true}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.server.port=8080
